" Name:         Firefly
" Description:  Vim color scheme for buggy summer nights
" Author:       Christian Rickert <rc.email@icloud.com>
" Maintainer:   Christian Rickert <rc.email@icloud.com>
" Website:      https://github.com/christianrickert/vim-firefly
" License:      Public domain
" Last Change:  2024 Aug 14

" Generated by Colortemplate v2.2.3

set background=dark

hi clear
let g:colors_name = 'firefly'

let s:t_Co = has('gui_running') ? -1 : (&t_Co ?? 0)
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')

hi! link Added diffAdded
hi! link Boolean Constant
hi! link Character Constant
hi! link Changed diffChanged
hi! link Conditional Statement
hi! link CurSearch IncSearch
hi! link CursorLineFold FoldColumn
hi! link CursorLineSign SignColumn
hi! link Debug Special
hi! link Define PreProc
hi! link Delimiter Special
hi! link Exception Statement
hi! link Float Constant
hi! link Function Identifier
hi! link Include PreProc
hi! link Keyword Statement
hi! link Label Statement
hi! link LineNrAbove LineNr
hi! link LineNrBelow LineNr
hi! link Macro PreProc
hi! link MessageWindow WarningMsg
hi! link Number Constant
hi! link Operator Statement
hi! link PmenuKind Pmenu
hi! link PmenuKindSel PmenuSel
hi! link PmenuExtra Pmenu
hi! link PmenuExtraSel PmenuSel
hi! link PmenuMatch Pmenu
hi! link PmenuMatchSel PmenuSel
hi! link PopupNotification WarningMsg
hi! link PopupSelected PmenuSel
hi! link PreCondit PreProc
hi! link QuickFixLine Search
hi! link Repeat Statement
hi! link Removed diffRemoved
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link StorageClass Type
hi! link String Constant
hi! link Structure Type
hi! link Tag Special
hi! link Typedef Type
hi! link debugBreakpoint SignColumn
hi! link debugPC SignColumn
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#000000', '#ff0000', '#00ff00', '#ffff00', '#0000ff', '#ff00ff', '#00ffff', '#ebebeb', '#d2d2d2', '#ff6400', '#64ff00', '#ffff64', '#0064ff', '#ff64ff', '#64ffff', '#e0e0ed']
endif
if get(g:, 'dark_transp_bg', 0) && !has('gui_running')
  hi Normal guifg=#fdf6e3 guibg=NONE gui=NONE cterm=NONE
  hi Terminal guifg=#fdf6e3 guibg=NONE gui=NONE cterm=NONE
else
  hi Normal guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
  hi Terminal guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
endif
hi ColorColumn guifg=fg guibg=#2a2a2a gui=NONE cterm=NONE
hi Conceal guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
hi Cursor guifg=#fdf6e3 guibg=#2a2a2a gui=reverse cterm=reverse
hi CursorColumn guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi CursorLine guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi CursorLineNr guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi DiffAdd guifg=#fdf6e3 guibg=#2a2a2a gui=reverse cterm=reverse
hi DiffChange guifg=#fdf6e3 guibg=#2a2a2a gui=reverse cterm=reverse
hi DiffDelete guifg=#fdf6e3 guibg=#2a2a2a gui=reverse cterm=reverse
hi DiffText guifg=#fdf6e3 guibg=#2a2a2a gui=bold,reverse cterm=bold,reverse
hi Directory guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi EndOfBuffer guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi ErrorMsg guifg=#fdf6e3 guibg=#2a2a2a gui=reverse cterm=reverse
hi FoldColumn guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi Folded guifg=#fdf6e3 guibg=#2a2a2a gui=italic cterm=italic
hi IncSearch guifg=#fdf6e3 guibg=#2a2a2a gui=standout cterm=reverse
hi LineNr guifg=#757575 guibg=#2a2a2a gui=NONE cterm=NONE
hi MatchParen guifg=#fdf6e3 guibg=#2a2a2a gui=reverse cterm=reverse
hi ModeMsg guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi MoreMsg guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi NonText guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi Pmenu guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi PmenuSbar guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi PmenuSel guifg=#fdf6e3 guibg=#2a2a2a gui=reverse cterm=reverse
hi PmenuThumb guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi Question guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi Search guifg=#fdf6e3 guibg=#2a2a2a gui=reverse cterm=reverse
hi SignColumn guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi SpecialKey guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi SpellBad guifg=#fdf6e3 guibg=#2a2a2a guisp=#ff0000 gui=NONE cterm=NONE
hi SpellCap guifg=#fdf6e3 guibg=#2a2a2a guisp=#0000ff gui=NONE cterm=NONE
hi SpellLocal guifg=#fdf6e3 guibg=#2a2a2a guisp=#ff00ff gui=NONE cterm=NONE
hi SpellRare guifg=#fdf6e3 guibg=#2a2a2a guisp=#00ffff gui=reverse cterm=reverse
hi StatusLine guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi StatusLineNC guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi TabLine guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi TabLineFill guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi TabLineSel guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi Title guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi VertSplit guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi Visual guifg=#fdf6e3 guibg=#2a2a2a gui=reverse cterm=reverse
hi VisualNOS guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi WarningMsg guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi WildMenu guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi Comment guifg=#de98fa guibg=NONE gui=italic cterm=italic
hi Constant guifg=#84baff guibg=NONE gui=NONE cterm=NONE
hi Error guifg=#fdf6e3 guibg=#2a2a2a gui=reverse cterm=reverse
hi Identifier guifg=#6de0a7 guibg=NONE gui=NONE cterm=NONE
hi Ignore guifg=#fdf6e3 guibg=NONE gui=NONE cterm=NONE
hi PreProc guifg=#fede46 guibg=NONE gui=NONE cterm=NONE
hi Special guifg=#84baff guibg=NONE gui=italic cterm=italic
hi Statement guifg=#ff8c7e guibg=NONE gui=NONE cterm=NONE
hi Todo guifg=#de98fa guibg=NONE gui=NONE cterm=NONE
hi Type guifg=#faae3d guibg=NONE gui=NONE cterm=NONE
hi Underlined guifg=#6da7e0 guibg=NONE gui=underline cterm=underline
hi CursorIM guifg=NONE guibg=fg gui=NONE cterm=NONE
hi ToolbarLine guifg=NONE guibg=#2a2a2a gui=NONE cterm=NONE
hi ToolbarButton guifg=#fdf6e3 guibg=#2a2a2a gui=bold cterm=bold
if !s:italics
  hi Folded gui=NONE cterm=NONE
  hi Comment gui=NONE cterm=NONE
  hi Special gui=NONE cterm=NONE
endif

if s:t_Co >= 256
  if get(g:, 'dark_transp_bg', 0)
    hi Normal ctermfg=249 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=249 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=249 ctermbg=106 cterm=NONE
    hi Terminal ctermfg=249 ctermbg=106 cterm=NONE
  endif
  hi ColorColumn ctermfg=fg ctermbg=106 cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=249 ctermbg=106 cterm=reverse
  hi CursorColumn ctermfg=249 ctermbg=106 cterm=NONE
  hi CursorLine ctermfg=249 ctermbg=106 cterm=NONE
  hi CursorLineNr ctermfg=249 ctermbg=106 cterm=NONE
  hi DiffAdd ctermfg=249 ctermbg=106 cterm=reverse
  hi DiffChange ctermfg=249 ctermbg=106 cterm=reverse
  hi DiffDelete ctermfg=249 ctermbg=106 cterm=reverse
  hi DiffText ctermfg=249 ctermbg=106 cterm=bold,reverse
  hi Directory ctermfg=249 ctermbg=106 cterm=NONE
  hi EndOfBuffer ctermfg=249 ctermbg=106 cterm=NONE
  hi ErrorMsg ctermfg=249 ctermbg=106 cterm=reverse
  hi FoldColumn ctermfg=249 ctermbg=106 cterm=NONE
  hi Folded ctermfg=249 ctermbg=106 cterm=italic
  hi IncSearch ctermfg=249 ctermbg=106 cterm=reverse
  hi LineNr ctermfg=158 ctermbg=106 cterm=NONE
  hi MatchParen ctermfg=249 ctermbg=106 cterm=reverse
  hi ModeMsg ctermfg=249 ctermbg=106 cterm=NONE
  hi MoreMsg ctermfg=249 ctermbg=106 cterm=NONE
  hi NonText ctermfg=249 ctermbg=106 cterm=NONE
  hi Pmenu ctermfg=249 ctermbg=106 cterm=NONE
  hi PmenuSbar ctermfg=249 ctermbg=106 cterm=NONE
  hi PmenuSel ctermfg=249 ctermbg=106 cterm=reverse
  hi PmenuThumb ctermfg=249 ctermbg=106 cterm=NONE
  hi Question ctermfg=249 ctermbg=106 cterm=NONE
  hi Search ctermfg=249 ctermbg=106 cterm=reverse
  hi SignColumn ctermfg=249 ctermbg=106 cterm=NONE
  hi SpecialKey ctermfg=249 ctermbg=106 cterm=NONE
  hi SpellBad ctermfg=249 ctermbg=106 cterm=NONE
  hi SpellCap ctermfg=249 ctermbg=106 cterm=NONE
  hi SpellLocal ctermfg=249 ctermbg=106 cterm=NONE
  hi SpellRare ctermfg=249 ctermbg=106 cterm=reverse
  hi StatusLine ctermfg=249 ctermbg=106 cterm=NONE
  hi StatusLineNC ctermfg=249 ctermbg=106 cterm=NONE
  hi TabLine ctermfg=249 ctermbg=106 cterm=NONE
  hi TabLineFill ctermfg=249 ctermbg=106 cterm=NONE
  hi TabLineSel ctermfg=249 ctermbg=106 cterm=NONE
  hi Title ctermfg=249 ctermbg=106 cterm=NONE
  hi VertSplit ctermfg=249 ctermbg=106 cterm=NONE
  hi Visual ctermfg=249 ctermbg=106 cterm=reverse
  hi VisualNOS ctermfg=249 ctermbg=106 cterm=NONE
  hi WarningMsg ctermfg=249 ctermbg=106 cterm=NONE
  hi WildMenu ctermfg=249 ctermbg=106 cterm=NONE
  hi Comment ctermfg=222 ctermbg=NONE cterm=italic
  hi Constant ctermfg=186 ctermbg=NONE cterm=NONE
  hi Error ctermfg=249 ctermbg=106 cterm=reverse
  hi Identifier ctermfg=167 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=249 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=224 ctermbg=NONE cterm=NONE
  hi Special ctermfg=186 ctermbg=NONE cterm=italic
  hi Statement ctermfg=140 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=222 ctermbg=NONE cterm=NONE
  hi Type ctermfg=184 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=153 ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=106 cterm=NONE
  hi ToolbarButton ctermfg=249 ctermbg=106 cterm=bold
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
    hi Special cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'dark_transp_bg', 0)
    hi Normal ctermfg=White ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=White ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=White ctermbg=DarkGray cterm=NONE
    hi Terminal ctermfg=White ctermbg=DarkGray cterm=NONE
  endif
  hi ColorColumn ctermfg=fg ctermbg=DarkGray cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=White ctermbg=DarkGray cterm=reverse
  hi CursorColumn ctermfg=White ctermbg=DarkGray cterm=NONE
  hi CursorLine ctermfg=White ctermbg=DarkGray cterm=NONE
  hi CursorLineNr ctermfg=White ctermbg=DarkGray cterm=NONE
  hi DiffAdd ctermfg=White ctermbg=DarkGray cterm=reverse
  hi DiffChange ctermfg=White ctermbg=DarkGray cterm=reverse
  hi DiffDelete ctermfg=White ctermbg=DarkGray cterm=reverse
  hi DiffText ctermfg=White ctermbg=DarkGray cterm=bold,reverse
  hi Directory ctermfg=White ctermbg=DarkGray cterm=NONE
  hi EndOfBuffer ctermfg=White ctermbg=DarkGray cterm=NONE
  hi ErrorMsg ctermfg=White ctermbg=DarkGray cterm=reverse
  hi FoldColumn ctermfg=White ctermbg=DarkGray cterm=NONE
  hi Folded ctermfg=White ctermbg=DarkGray cterm=italic
  hi IncSearch ctermfg=White ctermbg=DarkGray cterm=reverse
  hi LineNr ctermfg=Gray ctermbg=DarkGray cterm=NONE
  hi MatchParen ctermfg=White ctermbg=DarkGray cterm=reverse
  hi ModeMsg ctermfg=White ctermbg=DarkGray cterm=NONE
  hi MoreMsg ctermfg=White ctermbg=DarkGray cterm=NONE
  hi NonText ctermfg=White ctermbg=DarkGray cterm=NONE
  hi Pmenu ctermfg=White ctermbg=DarkGray cterm=NONE
  hi PmenuSbar ctermfg=White ctermbg=DarkGray cterm=NONE
  hi PmenuSel ctermfg=White ctermbg=DarkGray cterm=reverse
  hi PmenuThumb ctermfg=White ctermbg=DarkGray cterm=NONE
  hi Question ctermfg=White ctermbg=DarkGray cterm=NONE
  hi Search ctermfg=White ctermbg=DarkGray cterm=reverse
  hi SignColumn ctermfg=White ctermbg=DarkGray cterm=NONE
  hi SpecialKey ctermfg=White ctermbg=DarkGray cterm=NONE
  hi SpellBad ctermfg=White ctermbg=DarkGray cterm=NONE
  hi SpellCap ctermfg=White ctermbg=DarkGray cterm=NONE
  hi SpellLocal ctermfg=White ctermbg=DarkGray cterm=NONE
  hi SpellRare ctermfg=White ctermbg=DarkGray cterm=reverse
  hi StatusLine ctermfg=White ctermbg=DarkGray cterm=NONE
  hi StatusLineNC ctermfg=White ctermbg=DarkGray cterm=NONE
  hi TabLine ctermfg=White ctermbg=DarkGray cterm=NONE
  hi TabLineFill ctermfg=White ctermbg=DarkGray cterm=NONE
  hi TabLineSel ctermfg=White ctermbg=DarkGray cterm=NONE
  hi Title ctermfg=White ctermbg=DarkGray cterm=NONE
  hi VertSplit ctermfg=White ctermbg=DarkGray cterm=NONE
  hi Visual ctermfg=White ctermbg=DarkGray cterm=reverse
  hi VisualNOS ctermfg=White ctermbg=DarkGray cterm=NONE
  hi WarningMsg ctermfg=White ctermbg=DarkGray cterm=NONE
  hi WildMenu ctermfg=White ctermbg=DarkGray cterm=NONE
  hi Comment ctermfg=Magenta ctermbg=NONE cterm=italic
  hi Constant ctermfg=LightBlue ctermbg=NONE cterm=NONE
  hi Error ctermfg=White ctermbg=DarkGray cterm=reverse
  hi Identifier ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=White ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi Special ctermfg=LightBlue ctermbg=NONE cterm=italic
  hi Statement ctermfg=LightRed ctermbg=NONE cterm=NONE
  hi Todo ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Type ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=Blue ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=DarkGray cterm=NONE
  hi ToolbarButton ctermfg=White ctermbg=DarkGray cterm=bold
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
    hi Special cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 0
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi PopupSelected term=reverse
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  hi debugBreakpoint term=reverse
  hi debugPC term=reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: black         rgb(  0,   0,   0)        ~         Black
" Color: red           rgb(255,   0,   0)        ~         DarkRed
" Color: green         rgb(  0, 255,   0)        ~         DarkGreen
" Color: yellow        rgb(255, 255,   0)        ~         DarkYellow
" Color: blue          rgb(  0,   0, 255)        ~         DarkBlue
" Color: magenta       rgb(255,   0, 255)        ~         DarkMagenta
" Color: cyan          rgb(  0, 255, 255)        ~         DarkCyan
" Color: white         rgb(235, 235, 235)        ~         LightGrey
" Color: brightblack   rgb(210, 210, 210)        ~         DarkGrey
" Color: brightred     rgb(255, 100,   0)        ~         LightRed
" Color: brightgreen   rgb(100, 255,   0)        ~         LightGreen
" Color: brightyellow  rgb(255, 255, 100)        ~         LightYellow
" Color: brightblue    rgb(  0, 100, 255)        ~         LightBlue
" Color: brightmagenta rgb(255, 100, 255)        ~         LightMagenta
" Color: brightcyan    rgb(100, 255, 255)        ~         LightCyan
" Color: brightwhite   #e0e0ed                  231        White
" Color: cool_blue     #6da7e0                  153        Blue
" Color: light_blue    #84baff                  186        LightBlue
" Color: calm_teal     #6de0a7                  167        Cyan
" Color: soft_violet   #de98fa                  222        Magenta
" Color: vivid_orange  #faae3d                  184        Yellow
" Color: light_red     #ff8c7e                  140        LightRed
" Color: vivid_yellow  #fede46                  224        LightYellow
" Color: warm_white    #fdf6e3                  249        White
" Color: dark_warm_ash #2a2a2a                  106        DarkGray
" Color: medium_gray   #757575                  158        Gray
" Term colors: black red green yellow blue magenta cyan white
" Term colors: brightblack brightred brightgreen brightyellow
" Term colors: brightblue brightmagenta brightcyan brightwhite
" vim: et ts=8 sw=2 sts=2
