" Name:         Firefly
" Description:  Vim color scheme for buggy summer nights
" Author:       Christian Rickert <rc.email@icloud.com>
" Maintainer:   Christian Rickert <rc.email@icloud.com>
" Website:      https://me.org
" License:      Public domain
" Last Updated: Sat Aug 10 14:01:24 2024

" Generated by Colortemplate v2.2.3

set background=dark

hi clear
let g:colors_name = 'firefly'

let s:t_Co = has('gui_running') ? -1 : (&t_Co ?? 0)
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')

hi! link Added diffAdded
hi! link Boolean Constant
hi! link Character Constant
hi! link Changed diffChanged
hi! link Conditional Statement
hi! link CurSearch IncSearch
hi! link CursorLineFold FoldColumn
hi! link CursorLineSign SignColumn
hi! link Debug Special
hi! link Define PreProc
hi! link Delimiter Special
hi! link Exception Statement
hi! link Float Constant
hi! link Function Identifier
hi! link Include PreProc
hi! link Keyword Statement
hi! link Label Statement
hi! link LineNrAbove LineNr
hi! link LineNrBelow LineNr
hi! link Macro PreProc
hi! link MessageWindow WarningMsg
hi! link Number Constant
hi! link Operator Statement
hi! link PmenuKind Pmenu
hi! link PmenuKindSel PmenuSel
hi! link PmenuExtra Pmenu
hi! link PmenuExtraSel PmenuSel
hi! link PmenuMatch Pmenu
hi! link PmenuMatchSel PmenuSel
hi! link PopupNotification WarningMsg
hi! link PopupSelected PmenuSel
hi! link PreCondit PreProc
hi! link QuickFixLine Search
hi! link Repeat Statement
hi! link Removed diffRemoved
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link StorageClass Type
hi! link String Constant
hi! link Structure Type
hi! link Tag Special
hi! link Typedef Type
hi! link debugBreakpoint SignColumn
hi! link debugPC SignColumn
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#394759', '#ff0000', '#00ff00', '#ffff00', '#0000ff', '#ff00ff', '#00ffff', '#ebebeb', '#d2d2d2', '#ff6400', '#64ff00', '#ffff64', '#0064ff', '#ff64ff', '#64ffff', '#e0e0ed']
endif
if get(g:, 'firefly_transp_bg', 0) && !has('gui_running')
  hi Normal guifg=#ebebeb guibg=NONE gui=NONE cterm=NONE
  hi Terminal guifg=#ebebeb guibg=NONE gui=NONE cterm=NONE
else
  hi Normal guifg=#ebebeb guibg=#394759 gui=NONE cterm=NONE
  hi Terminal guifg=#ebebeb guibg=#394759 gui=NONE cterm=NONE
endif
hi Normal guifg=#fdf6e3 guibg=#2c2c2c gui=NONE cterm=NONE
hi Comment guifg=#1e88e5 guibg=NONE gui=italic cterm=italic
hi Constant guifg=#ffcdd2 guibg=NONE gui=NONE cterm=NONE
hi Identifier guifg=#80cbc4 guibg=NONE gui=NONE cterm=NONE
hi PreProc guifg=#e58ac2 guibg=NONE gui=NONE cterm=NONE
hi Special guifg=#fbc02d guibg=NONE gui=NONE cterm=NONE
hi Statement guifg=#ffeb3b guibg=NONE gui=NONE cterm=NONE
hi Type guifg=#cddc39 guibg=NONE gui=NONE cterm=NONE
if !s:italics
  hi Comment gui=NONE cterm=NONE
endif

if s:t_Co >= 256
  if get(g:, 'firefly_transp_bg', 0)
    hi Normal ctermfg=255 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=255 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=255 ctermbg=238 cterm=NONE
    hi Terminal ctermfg=255 ctermbg=238 cterm=NONE
  endif
  hi Normal ctermfg=230 ctermbg=235 cterm=NONE
  hi Comment ctermfg=33 ctermbg=NONE cterm=italic
  hi Constant ctermfg=224 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=123 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=219 ctermbg=NONE cterm=NONE
  hi Special ctermfg=226 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=229 ctermbg=NONE cterm=NONE
  hi Type ctermfg=190 ctermbg=NONE cterm=NONE
  if !s:italics
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'firefly_transp_bg', 0)
    hi Normal ctermfg=LightGrey ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=LightGrey ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi Terminal ctermfg=LightGrey ctermbg=Black cterm=NONE
  endif
  hi Normal ctermfg=White ctermbg=Darkgray cterm=NONE
  hi Comment ctermfg=Blue ctermbg=NONE cterm=italic
  hi Constant ctermfg=Lightred ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Special ctermfg=Lightyellow ctermbg=NONE cterm=NONE
  hi Statement ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Type ctermfg=Yellow ctermbg=NONE cterm=NONE
  if !s:italics
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
"  Color: black         rgb( 57,  71,  89)        ~         Black
"  Color: red           rgb(255,   0,   0)        ~         DarkRed
"  Color: green         rgb(  0, 255,   0)        ~         DarkGreen
"  Color: yellow        rgb(255, 255,   0)        ~         DarkYellow
"  Color: blue          rgb(  0,   0, 255)        ~         DarkBlue
"  Color: magenta       rgb(255,   0, 255)        ~         DarkMagenta
"  Color: cyan          rgb(  0, 255, 255)        ~         DarkCyan
"  Color: white         rgb(235, 235, 235)        ~         LightGrey
"  Color: brightblack   rgb(210, 210, 210)        ~         DarkGrey
"  Color: brightred     rgb(255, 100,   0)        ~         LightRed
"  Color: brightgreen   rgb(100, 255,   0)        ~         LightGreen
"  Color: brightyellow  rgb(255, 255, 100)        ~         LightYellow
"  Color: brightblue    rgb(  0, 100, 255)        ~         LightBlue
"  Color: brightmagenta rgb(255, 100, 255)        ~         LightMagenta
"  Color: brightcyan    rgb(100, 255, 255)        ~         LightCyan
" Color: brightwhite   #e0e0ed                  231        White
" Color: cool_blue           #1e88e5             33        Blue
" Color: earthy_brown        #6d4c41             94        Brown
" Color: faded_walnut        #4c3b30             94        Brown
" Color: calm_teal_cmpl      #80cbc4            123        Cyan
" Color: olive_green         #8bc34a            148        Green
" Color: light_gray          #bdbdbd            145        Lightgray
" Color: warm_red            #d32f2f            160        Red
" Color: gentle_lime_cmpl    #cddc39            190        Yellow
" Color: warm_orange         #f57c00            214        Yellow
" Color: soft_coral          #e57373            210        Lightred
" Color: soft_pink_cmpl      #e58ac2            219        Magenta
" Color: misty_rose_cmpl     #ffcdd2            224        Lightred
" Color: pale_peach_cmpl     #ffccbc            224        Lightyellow
" Color: golden_yellow       #fbc02d            226        Lightyellow
" Color: soft_amber_cmpl     #ffeb3b            229        Yellow
" Color: warm_white          #fdf6e3            230        White
" Color: soft_charcoal       #2c2c2c            235        Darkgray
" Color: warm_ash            #3a3a3a            236        Darkgray
" Color: dark_gray           #424242            237        Darkgray
" Color: deep_slate_blue     #333a56            238        Darkblue
" Color: muted_olive         #4b4f3e            239        Brown
" Color: medium_gray         #757575            240        Gray
" Term colors: black red green yellow blue magenta cyan white
" Term colors: brightblack brightred brightgreen brightyellow
" Term colors: brightblue brightmagenta brightcyan brightwhite
" vim: et ts=8 sw=2 sts=2
