vim9script

# Name:         Firefly (*anopia)
# Description:  Vim color scheme for buggy summer nights (protanopia & deuteranopia)
# Author:       Christian Rickert <rc.email@icloud.com>
# Maintainer:   Christian Rickert <rc.email@icloud.com>
# URL:          https://me.org
# License:      MIT
# Last Change:  Mon Dec 29 14:05:04 2025

# Generated by Colortemplate v3.0.0-beta10

set background=dark

hi clear
g:colors_name = 'firefly_anopia'

# This is copied verbatim at the start of the output.
# Interpolation allows you to replace metadata in the
# output. For instance: Christian Rickert <rc.email@icloud.com>.

const t_Co = has('gui_running') ? 16777216 : str2nr(&t_Co)
const tgc = has('termguicolors') && &termguicolors

g:terminal_ansi_colors = ['#2a2a2a', '#ff0000', '#00ff00', '#ffff00', '#0000ff', '#ff00ff', '#00ffff', '#fdf6e3', '#d2d2d2', '#ff6400', '#64ff00', '#ffff64', '#0064ff', '#ff64ff', '#64ffff', '#e0e0ed']

# Multiple verbatim blocks are possible: no matter where
# they appear in the template, they are concatenated at
# the start of the output. Since this block appears after
# the Background directive, the background value can be
# interpolated: the background is set to dark.
# This block appears after Color directives, so colors can
# be interpolated, too: for instance, black is defined as
# #2a2a2a in the GUI, and 235 or Black in terminals.

const transp_bg = get(g:, 'fy_transp_bg', 0)

hi! link Added diffAdded
hi! link Boolean Constant
hi! link Changed diffChanged
hi! link Character Constant
hi! link ComplMatchIns Normal
hi! link Conditional Statement
hi! link CurSearch IncSearch
hi! link CursorLineFold FoldColumn
hi! link CursorLineSign SignColumn
hi! link Debug Special
hi! link Define PreProc
hi! link Delimiter Special
hi! link Exception Statement
hi! link Float Constant
hi! link Function Identifier
hi! link Include PreProc
hi! link Keyword Statement
hi! link Label Statement
hi! link Macro PreProc
hi! link MessageWindow WarningMsg
hi! link Number Constant
hi! link Operator Statement
hi! link PmenuExtra Pmenu
hi! link PmenuExtraSel PmenuSel
hi! link PmenuKind Pmenu
hi! link PmenuKindSel PmenuSel
hi! link PmenuMatch Pmenu
hi! link PmenuMatchSel PmenuSel
hi! link PopupNotification WarningMsg
hi! link PopupSelected PmenuSel
hi! link PreCondit PreProc
hi! link PreInsert NonText
hi! link QuickFixLine Search
hi! link Removed diffRemoved
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link StorageClass Type
hi! link String Constant
hi! link Structure Type
hi! link Tag Special
hi! link Typedef Type
hi! link debugBreakpoint SignColumn
hi! link debugPC SignColumn
hi! link lCursor Cursor

hi Normal guifg=#fdf6e3 guibg=#2a2a2a guisp=NONE gui=NONE ctermfg=255 ctermbg=235 cterm=NONE term=NONE
hi ALEError guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE term=NONE
hi ALEErrorSign guifg=#ff5c8d guibg=NONE guisp=NONE gui=NONE ctermfg=204 ctermbg=NONE cterm=NONE term=NONE
hi ALEInfo guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE term=NONE
hi ALEInfoSign guifg=#00d4aa guibg=NONE guisp=NONE gui=NONE ctermfg=043 ctermbg=NONE cterm=NONE term=NONE
hi ALEVirtualTextError guifg=#ff5c8d guibg=NONE guisp=NONE gui=NONE ctermfg=204 ctermbg=NONE cterm=NONE term=NONE
hi ALEVirtualTextInfo guifg=#00d4aa guibg=NONE guisp=NONE gui=NONE ctermfg=043 ctermbg=NONE cterm=NONE term=NONE
hi ALEVirtualTextWarning guifg=#ffed4e guibg=NONE guisp=NONE gui=NONE ctermfg=228 ctermbg=NONE cterm=NONE term=NONE
hi ALEWarning guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE term=NONE
hi ALEWarningSign guifg=#ffed4e guibg=NONE guisp=NONE gui=NONE ctermfg=228 ctermbg=NONE cterm=NONE term=NONE
hi Bold guifg=#fdf6e3 guibg=NONE guisp=NONE gui=bold ctermfg=255 ctermbg=NONE cterm=bold term=bold
hi BoldItalic guifg=#fdf6e3 guibg=NONE guisp=NONE gui=bold,italic ctermfg=255 ctermbg=NONE cterm=bold,italic term=bold,italic
hi ColorColumn guifg=fg guibg=#2a2a2a guisp=NONE gui=NONE ctermfg=fg ctermbg=235 cterm=NONE term=reverse
hi Comment guifg=#b366ff guibg=NONE guisp=NONE gui=NONE ctermfg=135 ctermbg=NONE cterm=NONE term=italic
hi Conceal guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE term=NONE
hi Constant guifg=#7db8ff guibg=NONE guisp=NONE gui=NONE ctermfg=111 ctermbg=NONE cterm=NONE term=bold,italic
hi Cursor guifg=#fdf6e3 guibg=#2a2a2a guisp=NONE gui=reverse ctermfg=255 ctermbg=235 cterm=reverse term=NONE
hi CursorColumn guifg=#fdf6e3 guibg=#2a2a2a guisp=NONE gui=NONE ctermfg=255 ctermbg=235 cterm=NONE term=reverse
hi CursorIM guifg=#fdf6e3 guibg=#2a2a2a guisp=NONE gui=reverse ctermfg=255 ctermbg=235 cterm=reverse term=NONE
hi CursorLine guifg=#fdf6e3 guibg=#2a2a2a guisp=NONE gui=NONE ctermfg=255 ctermbg=235 cterm=NONE term=underline
hi CursorLineNr guifg=#fdf6e3 guibg=#2a2a2a guisp=NONE gui=NONE ctermfg=255 ctermbg=235 cterm=NONE term=bold,italic,reverse,underline
hi DiffAdd guifg=#00d4aa guibg=#2a2a2a guisp=NONE gui=reverse ctermfg=043 ctermbg=235 cterm=reverse term=reverse,underline
hi DiffChange guifg=#ffed4e guibg=#2a2a2a guisp=NONE gui=reverse ctermfg=228 ctermbg=235 cterm=reverse term=reverse,underline
hi DiffDelete guifg=#ff5c8d guibg=#2a2a2a guisp=NONE gui=reverse ctermfg=204 ctermbg=235 cterm=reverse term=reverse,underline
hi DiffText guifg=#fdf6e3 guibg=#2a2a2a guisp=NONE gui=bold,reverse ctermfg=255 ctermbg=235 cterm=bold,reverse term=bold,reverse,underline
hi Directory guifg=#fdf6e3 guibg=#2a2a2a guisp=NONE gui=NONE ctermfg=255 ctermbg=235 cterm=NONE term=NONE
hi EndOfBuffer guifg=#757575 guibg=#2a2a2a guisp=NONE gui=NONE ctermfg=241 ctermbg=235 cterm=NONE term=NONE
hi Error guifg=#ff5c8d guibg=NONE guisp=NONE gui=NONE ctermfg=204 ctermbg=NONE cterm=NONE term=reverse
hi ErrorMsg guifg=#ff5c8d guibg=#2a2a2a guisp=NONE gui=NONE ctermfg=204 ctermbg=235 cterm=NONE term=bold,italic,reverse
hi FoldColumn guifg=#fdf6e3 guibg=#2a2a2a guisp=NONE gui=NONE ctermfg=255 ctermbg=235 cterm=NONE term=reverse
hi Folded guifg=#757575 guibg=#2a2a2a guisp=NONE gui=NONE ctermfg=241 ctermbg=235 cterm=NONE term=italic,reverse,underline
hi Identifier guifg=#00d4aa guibg=NONE guisp=NONE gui=NONE ctermfg=043 ctermbg=NONE cterm=NONE term=italic
hi Ignore guifg=#fdf6e3 guibg=NONE guisp=NONE gui=NONE ctermfg=255 ctermbg=NONE cterm=NONE term=NONE
hi IncSearch guifg=#fdf6e3 guibg=#757575 guisp=NONE gui=NONE ctermfg=255 ctermbg=241 cterm=NONE term=bold,italic,reverse
hi Italic guifg=#fdf6e3 guibg=NONE guisp=NONE gui=italic ctermfg=255 ctermbg=NONE cterm=italic term=italic
hi LineNr guifg=#fdf6e3 guibg=#2a2a2a guisp=NONE gui=NONE ctermfg=255 ctermbg=235 cterm=NONE term=reverse
hi LineNrAbove guifg=#757575 guibg=#2a2a2a guisp=NONE gui=NONE ctermfg=241 ctermbg=235 cterm=NONE term=NONE
hi LineNrBelow guifg=#757575 guibg=#2a2a2a guisp=NONE gui=NONE ctermfg=241 ctermbg=235 cterm=NONE term=NONE
hi MatchParen guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse term=bold,underline
hi ModeMsg guifg=#fdf6e3 guibg=#2a2a2a guisp=NONE gui=reverse ctermfg=255 ctermbg=235 cterm=reverse term=NONE
hi MoreMsg guifg=#00d4aa guibg=#2a2a2a guisp=NONE gui=NONE ctermfg=043 ctermbg=235 cterm=NONE term=NONE
hi NonText guifg=#fdf6e3 guibg=#2a2a2a guisp=NONE gui=NONE ctermfg=255 ctermbg=235 cterm=NONE term=NONE
hi Pmenu guifg=#fdf6e3 guibg=#757575 guisp=NONE gui=NONE ctermfg=255 ctermbg=241 cterm=NONE term=reverse
hi PmenuSbar guifg=#fdf6e3 guibg=#2a2a2a guisp=NONE gui=NONE ctermfg=255 ctermbg=235 cterm=NONE term=NONE
hi PmenuSel guifg=#fdf6e3 guibg=#2a2a2a guisp=NONE gui=reverse ctermfg=255 ctermbg=235 cterm=reverse term=NONE
hi PmenuThumb guifg=#fdf6e3 guibg=#2a2a2a guisp=NONE gui=NONE ctermfg=255 ctermbg=235 cterm=NONE term=NONE
hi PreProc guifg=#ffed4e guibg=NONE guisp=NONE gui=NONE ctermfg=228 ctermbg=NONE cterm=NONE term=italic
hi Question guifg=#fdf6e3 guibg=#2a2a2a guisp=NONE gui=NONE ctermfg=255 ctermbg=235 cterm=NONE term=standout
hi Search guifg=#fdf6e3 guibg=#757575 guisp=NONE gui=NONE ctermfg=255 ctermbg=241 cterm=NONE term=italic,underline
hi SignColumn guifg=#fdf6e3 guibg=#2a2a2a guisp=NONE gui=NONE ctermfg=255 ctermbg=235 cterm=NONE term=reverse
hi Special guifg=#7db8ff guibg=NONE guisp=NONE gui=NONE ctermfg=111 ctermbg=NONE cterm=NONE term=bold,italic
hi SpecialKey guifg=#fdf6e3 guibg=#2a2a2a guisp=NONE gui=NONE ctermfg=255 ctermbg=235 cterm=NONE term=bold
hi SpellBad guifg=#fdf6e3 guibg=#2a2a2a guisp=#ff0000 gui=NONE ctermfg=255 ctermbg=235 cterm=NONE term=italic,underline ctermul=196
hi SpellCap guifg=#fdf6e3 guibg=#2a2a2a guisp=#0000ff gui=NONE ctermfg=255 ctermbg=235 cterm=NONE term=italic,underline ctermul=21
hi SpellLocal guifg=#fdf6e3 guibg=#2a2a2a guisp=#ff00ff gui=NONE ctermfg=255 ctermbg=235 cterm=NONE term=italic,underline ctermul=201
hi SpellRare guifg=#fdf6e3 guibg=#2a2a2a guisp=#00ffff gui=reverse ctermfg=255 ctermbg=235 cterm=reverse term=italic,underline ctermul=51
hi Statement guifg=#ff5c8d guibg=NONE guisp=NONE gui=NONE ctermfg=204 ctermbg=NONE cterm=NONE term=bold
hi StatusLine guifg=#fdf6e3 guibg=#2a2a2a guisp=NONE gui=reverse ctermfg=255 ctermbg=235 cterm=reverse term=bold,reverse
hi StatusLineNC guifg=#fdf6e3 guibg=#757575 guisp=NONE gui=NONE ctermfg=255 ctermbg=241 cterm=NONE term=reverse
hi TabLine guifg=#fdf6e3 guibg=#2a2a2a guisp=NONE gui=NONE ctermfg=255 ctermbg=235 cterm=NONE term=italic,reverse,underline
hi TabLineFill guifg=#fdf6e3 guibg=#2a2a2a guisp=NONE gui=NONE ctermfg=255 ctermbg=235 cterm=NONE term=reverse,underline
hi TabLineSel guifg=#fdf6e3 guibg=#2a2a2a guisp=NONE gui=NONE ctermfg=255 ctermbg=235 cterm=NONE term=bold
hi Terminal guifg=#fdf6e3 guibg=#2a2a2a guisp=NONE gui=NONE ctermfg=255 ctermbg=235 cterm=NONE term=NONE
hi Title guifg=#fdf6e3 guibg=#2a2a2a guisp=NONE gui=NONE ctermfg=255 ctermbg=235 cterm=NONE term=bold
hi Todo guifg=#ffed4e guibg=NONE guisp=NONE gui=reverse ctermfg=228 ctermbg=NONE cterm=reverse term=bold,underline
hi ToolbarButton guifg=#fdf6e3 guibg=#2a2a2a guisp=NONE gui=bold ctermfg=255 ctermbg=235 cterm=bold term=bold,reverse
hi ToolbarLine guifg=NONE guibg=#2a2a2a guisp=NONE gui=NONE ctermfg=NONE ctermbg=235 cterm=NONE term=reverse
hi Type guifg=#ff9500 guibg=NONE guisp=NONE gui=NONE ctermfg=208 ctermbg=NONE cterm=NONE term=bold
hi Underlined guifg=#7db8ff guibg=NONE guisp=NONE gui=underline ctermfg=111 ctermbg=NONE cterm=underline term=underline
hi VertSplit guifg=#fdf6e3 guibg=#2a2a2a guisp=NONE gui=NONE ctermfg=255 ctermbg=235 cterm=NONE term=reverse
hi Visual guifg=#fdf6e3 guibg=#757575 guisp=NONE gui=NONE ctermfg=255 ctermbg=241 cterm=NONE term=reverse
hi VisualNOS guifg=#fdf6e3 guibg=#2a2a2a guisp=NONE gui=NONE ctermfg=255 ctermbg=235 cterm=NONE term=NONE
hi WarningMsg guifg=#ffed4e guibg=#2a2a2a guisp=NONE gui=NONE ctermfg=228 ctermbg=235 cterm=NONE term=standout
hi WildMenu guifg=#fdf6e3 guibg=#2a2a2a guisp=NONE gui=NONE ctermfg=255 ctermbg=235 cterm=NONE term=bold

if has('gui_running') || tgc
  if transp_bg == 1
    hi Normal guifg=#fdf6e3 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  endif
endif

if tgc || t_Co >= 256
  if transp_bg == 1
    hi Normal ctermfg=255 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=255 ctermbg=NONE cterm=NONE
  endif
  finish
endif

if t_Co >= 8
  hi Normal ctermfg=White ctermbg=Black cterm=NONE
  hi ALEError ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ALEErrorSign ctermfg=Red ctermbg=NONE cterm=NONE
  hi ALEInfo ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ALEInfoSign ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi ALEVirtualTextError ctermfg=Red ctermbg=NONE cterm=NONE
  hi ALEVirtualTextInfo ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi ALEVirtualTextWarning ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi ALEWarning ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ALEWarningSign ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Bold ctermfg=White ctermbg=NONE cterm=bold
  hi BoldItalic ctermfg=White ctermbg=NONE cterm=bold,italic
  hi ColorColumn ctermfg=fg ctermbg=Black cterm=NONE
  hi Comment ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Constant ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=White ctermbg=Black cterm=reverse
  hi CursorColumn ctermfg=White ctermbg=Black cterm=NONE
  hi CursorIM ctermfg=White ctermbg=Black cterm=reverse
  hi CursorLine ctermfg=White ctermbg=Black cterm=NONE
  hi CursorLineNr ctermfg=White ctermbg=Black cterm=NONE
  hi DiffAdd ctermfg=Cyan ctermbg=Black cterm=reverse
  hi DiffChange ctermfg=Yellow ctermbg=Black cterm=reverse
  hi DiffDelete ctermfg=Red ctermbg=Black cterm=reverse
  hi DiffText ctermfg=White ctermbg=Black cterm=bold,reverse
  hi Directory ctermfg=White ctermbg=Black cterm=NONE
  hi EndOfBuffer ctermfg=DarkGray ctermbg=Black cterm=NONE
  hi Error ctermfg=Red ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=Red ctermbg=Black cterm=NONE
  hi FoldColumn ctermfg=White ctermbg=Black cterm=NONE
  hi Folded ctermfg=DarkGray ctermbg=Black cterm=NONE
  hi Identifier ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=White ctermbg=NONE cterm=NONE
  hi IncSearch ctermfg=White ctermbg=DarkGray cterm=NONE
  hi Italic ctermfg=White ctermbg=NONE cterm=italic
  hi LineNr ctermfg=White ctermbg=Black cterm=NONE
  hi LineNrAbove ctermfg=DarkGray ctermbg=Black cterm=NONE
  hi LineNrBelow ctermfg=DarkGray ctermbg=Black cterm=NONE
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=reverse
  hi ModeMsg ctermfg=White ctermbg=Black cterm=reverse
  hi MoreMsg ctermfg=Cyan ctermbg=Black cterm=NONE
  hi NonText ctermfg=White ctermbg=Black cterm=NONE
  hi Pmenu ctermfg=White ctermbg=DarkGray cterm=NONE
  hi PmenuSbar ctermfg=White ctermbg=Black cterm=NONE
  hi PmenuSel ctermfg=White ctermbg=Black cterm=reverse
  hi PmenuThumb ctermfg=White ctermbg=Black cterm=NONE
  hi PreProc ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Question ctermfg=White ctermbg=Black cterm=NONE
  hi Search ctermfg=White ctermbg=DarkGray cterm=NONE
  hi SignColumn ctermfg=White ctermbg=Black cterm=NONE
  hi Special ctermfg=Blue ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=White ctermbg=Black cterm=NONE
  hi SpellBad ctermfg=White ctermbg=Black cterm=NONE ctermul=DarkRed
  hi SpellCap ctermfg=White ctermbg=Black cterm=NONE ctermul=DarkBlue
  hi SpellLocal ctermfg=White ctermbg=Black cterm=NONE ctermul=DarkMagenta
  hi SpellRare ctermfg=White ctermbg=Black cterm=reverse ctermul=DarkCyan
  hi Statement ctermfg=Red ctermbg=NONE cterm=NONE
  hi StatusLine ctermfg=White ctermbg=Black cterm=reverse
  hi StatusLineNC ctermfg=White ctermbg=DarkGray cterm=NONE
  hi TabLine ctermfg=White ctermbg=Black cterm=NONE
  hi TabLineFill ctermfg=White ctermbg=Black cterm=NONE
  hi TabLineSel ctermfg=White ctermbg=Black cterm=NONE
  hi Terminal ctermfg=White ctermbg=Black cterm=NONE
  hi Title ctermfg=White ctermbg=Black cterm=NONE
  hi Todo ctermfg=Yellow ctermbg=NONE cterm=reverse
  hi ToolbarButton ctermfg=White ctermbg=Black cterm=bold
  hi ToolbarLine ctermfg=NONE ctermbg=Black cterm=NONE
  hi Type ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=Blue ctermbg=NONE cterm=underline
  hi VertSplit ctermfg=White ctermbg=Black cterm=NONE
  hi Visual ctermfg=White ctermbg=DarkGray cterm=NONE
  hi VisualNOS ctermfg=White ctermbg=Black cterm=NONE
  hi WarningMsg ctermfg=Yellow ctermbg=Black cterm=NONE
  hi WildMenu ctermfg=White ctermbg=Black cterm=NONE
  if transp_bg == 1
    hi Normal ctermfg=White ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=White ctermbg=NONE cterm=NONE
  endif
  finish
endif

if t_Co >= 0
  hi ComplMatchIns term=NONE
  hi PopupSelected term=reverse
  hi PreInsert term=NONE
  hi debugBreakpoint term=reverse
  hi debugPC term=reverse
  finish
endif

# Background: dark
# 
# ───────────────────────────────────────────────────────
#           Name     GUI Base256 Base256Hex       Base16
# ───────────────────────────────────────────────────────
#          black #2a2a2a     235    #262626        Black
#           blue #0000ff      21    #0000ff     DarkBlue
#    brightblack #d2d2d2     252    #d0d0d0     DarkGrey
#     brightblue #0064ff      27    #005fff    LightBlue
#     brightcyan #64ffff      87    #5fffff    LightCyan
#    brightgreen #64ff00      82    #5fff00   LightGreen
#  brightmagenta #ff64ff     207    #ff5fff LightMagenta
#      brightred #ff6400     202    #ff5f00     LightRed
#    brightwhite #e0e0ed     254    #e4e4e4        White
#   brightyellow #ffff64     227    #ffff5f  LightYellow
#      calm_teal #00d4aa     043    #00d7af         Cyan
#           cyan #00ffff      51    #00ffff     DarkCyan
#  dark_warm_ash #2a2a2a     235    #262626        Black
#          green #00ff00      46    #00ff00    DarkGreen
#     light_blue #7db8ff     111    #87afff         Blue
#      light_red #ff5c8d     204    #ff5f87          Red
#        magenta #ff00ff     201    #ff00ff  DarkMagenta
#    medium_gray #757575     241    #626262     DarkGray
#            red #ff0000     196    #ff0000      DarkRed
#    soft_violet #b366ff     135    #af5fff      Magenta
#   vivid_orange #ff9500     208    #ff8700       Yellow
#   vivid_yellow #ffed4e     228    #ffff87       Yellow
#     warm_white #fdf6e3     255    #eeeeee        White
#          white #fdf6e3     255    #eeeeee        White
#         yellow #ffff00     226    #ffff00   DarkYellow

# vim: et ts=8 sw=2 sts=2
