" Name:         Firefly
" Description:  Vim color scheme for buggy summer nights
" Author:       Christian Rickert <rc.email@icloud.com>
" Maintainer:   Christian Rickert <rc.email@icloud.com>
" Website:      https://github.com/christianrickert/vim-firefly
" License:      Public domain
" Last Change:  2024 Aug 11

" Generated by Colortemplate v2.2.3

set background=dark

hi clear
let g:colors_name = 'firefly'

let s:t_Co = has('gui_running') ? -1 : (&t_Co ?? 0)
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')

hi! link Added diffAdded
hi! link Boolean Constant
hi! link Character Constant
hi! link Changed diffChanged
hi! link Conditional Statement
hi! link CurSearch IncSearch
hi! link CursorLineFold FoldColumn
hi! link CursorLineSign SignColumn
hi! link Debug Special
hi! link Define PreProc
hi! link Delimiter Special
hi! link Exception Statement
hi! link Float Constant
hi! link Function Identifier
hi! link Include PreProc
hi! link Keyword Statement
hi! link Label Statement
hi! link LineNrAbove LineNr
hi! link LineNrBelow LineNr
hi! link Macro PreProc
hi! link MessageWindow WarningMsg
hi! link Number Constant
hi! link Operator Statement
hi! link PmenuKind Pmenu
hi! link PmenuKindSel PmenuSel
hi! link PmenuExtra Pmenu
hi! link PmenuExtraSel PmenuSel
hi! link PmenuMatch Pmenu
hi! link PmenuMatchSel PmenuSel
hi! link PopupNotification WarningMsg
hi! link PopupSelected PmenuSel
hi! link PreCondit PreProc
hi! link QuickFixLine Search
hi! link Repeat Statement
hi! link Removed diffRemoved
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link StorageClass Type
hi! link String Constant
hi! link Structure Type
hi! link Tag Special
hi! link Typedef Type
hi! link debugBreakpoint SignColumn
hi! link debugPC SignColumn
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#000000', '#ff0000', '#00ff00', '#ffff00', '#0000ff', '#ff00ff', '#00ffff', '#ebebeb', '#d2d2d2', '#ff6400', '#64ff00', '#ffff64', '#0064ff', '#ff64ff', '#64ffff', '#e0e0ed']
endif
if get(g:, 'dark_transp_bg', 0) && !has('gui_running')
  hi Normal guifg=#fdf6e3 guibg=NONE gui=NONE cterm=NONE
  hi Terminal guifg=#fdf6e3 guibg=NONE gui=NONE cterm=NONE
else
  hi Normal guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
  hi Terminal guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
endif
hi ColorColumn guifg=fg guibg=#2a2a2a gui=NONE cterm=NONE
hi Conceal guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
hi Cursor guifg=#fdf6e3 guibg=#2a2a2a gui=reverse cterm=reverse
hi CursorColumn guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi CursorLine guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi CursorLineNr guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi DiffAdd guifg=#fdf6e3 guibg=#2a2a2a gui=reverse cterm=reverse
hi DiffChange guifg=#fdf6e3 guibg=#2a2a2a gui=reverse cterm=reverse
hi DiffDelete guifg=#fdf6e3 guibg=#2a2a2a gui=reverse cterm=reverse
hi DiffText guifg=#fdf6e3 guibg=#2a2a2a gui=bold,reverse cterm=bold,reverse
hi Directory guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi EndOfBuffer guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi ErrorMsg guifg=#fdf6e3 guibg=#2a2a2a gui=reverse cterm=reverse
hi FoldColumn guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi Folded guifg=#fdf6e3 guibg=#2a2a2a gui=italic cterm=italic
hi IncSearch guifg=#fdf6e3 guibg=#2a2a2a gui=standout cterm=reverse
hi LineNr guifg=#757575 guibg=#2a2a2a gui=NONE cterm=NONE
hi MatchParen guifg=#fdf6e3 guibg=#2a2a2a gui=reverse cterm=reverse
hi ModeMsg guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi MoreMsg guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi NonText guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi Pmenu guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi PmenuSbar guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi PmenuSel guifg=#fdf6e3 guibg=#2a2a2a gui=reverse cterm=reverse
hi PmenuThumb guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi Question guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi Search guifg=#fdf6e3 guibg=#2a2a2a gui=reverse cterm=reverse
hi SignColumn guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi SpecialKey guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi SpellBad guifg=#fdf6e3 guibg=#2a2a2a guisp=#ff0000 gui=NONE cterm=NONE
hi SpellCap guifg=#fdf6e3 guibg=#2a2a2a guisp=#0000ff gui=NONE cterm=NONE
hi SpellLocal guifg=#fdf6e3 guibg=#2a2a2a guisp=#ff00ff gui=NONE cterm=NONE
hi SpellRare guifg=#fdf6e3 guibg=#2a2a2a guisp=#00ffff gui=reverse cterm=reverse
hi StatusLine guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi StatusLineNC guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi TabLine guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi TabLineFill guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi TabLineSel guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi Title guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi VertSplit guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi Visual guifg=#fdf6e3 guibg=#2a2a2a gui=reverse cterm=reverse
hi VisualNOS guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi WarningMsg guifg=#d32f2f guibg=#2a2a2a gui=NONE cterm=NONE
hi WildMenu guifg=#fdf6e3 guibg=#2a2a2a gui=NONE cterm=NONE
hi Comment guifg=#757575 guibg=NONE gui=italic cterm=italic
hi Constant guifg=#2f81d3 guibg=NONE gui=NONE cterm=NONE
hi Error guifg=#fdf6e3 guibg=#2a2a2a gui=reverse cterm=reverse
hi Identifier guifg=#2fd381 guibg=NONE gui=NONE cterm=NONE
hi Ignore guifg=#fdf6e3 guibg=NONE gui=NONE cterm=NONE
hi PreProc guifg=#f9a30e guibg=NONE gui=NONE cterm=NONE
hi Special guifg=#2f81d3 guibg=NONE gui=italic cterm=italic
hi Statement guifg=#ff5b50 guibg=NONE gui=NONE cterm=NONE
hi Todo guifg=#d06cf8 guibg=NONE gui=NONE cterm=NONE
hi Type guifg=#fedf13 guibg=NONE gui=NONE cterm=NONE
hi Underlined guifg=#2f81d3 guibg=NONE gui=underline cterm=underline
hi CursorIM guifg=NONE guibg=fg gui=NONE cterm=NONE
hi ToolbarLine guifg=NONE guibg=#2a2a2a gui=NONE cterm=NONE
hi ToolbarButton guifg=#fdf6e3 guibg=#2a2a2a gui=bold cterm=bold
if !s:italics
  hi Folded gui=NONE cterm=NONE
  hi Comment gui=NONE cterm=NONE
  hi Special gui=NONE cterm=NONE
endif

if s:t_Co >= 256
  if get(g:, 'dark_transp_bg', 0)
    hi Normal ctermfg=230 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=230 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=230 ctermbg=234 cterm=NONE
    hi Terminal ctermfg=230 ctermbg=234 cterm=NONE
  endif
  hi ColorColumn ctermfg=fg ctermbg=234 cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=230 ctermbg=234 cterm=reverse
  hi CursorColumn ctermfg=230 ctermbg=234 cterm=NONE
  hi CursorLine ctermfg=230 ctermbg=234 cterm=NONE
  hi CursorLineNr ctermfg=230 ctermbg=234 cterm=NONE
  hi DiffAdd ctermfg=230 ctermbg=234 cterm=reverse
  hi DiffChange ctermfg=230 ctermbg=234 cterm=reverse
  hi DiffDelete ctermfg=230 ctermbg=234 cterm=reverse
  hi DiffText ctermfg=230 ctermbg=234 cterm=bold,reverse
  hi Directory ctermfg=230 ctermbg=234 cterm=NONE
  hi EndOfBuffer ctermfg=230 ctermbg=234 cterm=NONE
  hi ErrorMsg ctermfg=230 ctermbg=234 cterm=reverse
  hi FoldColumn ctermfg=230 ctermbg=234 cterm=NONE
  hi Folded ctermfg=230 ctermbg=234 cterm=italic
  hi IncSearch ctermfg=230 ctermbg=234 cterm=reverse
  hi LineNr ctermfg=240 ctermbg=234 cterm=NONE
  hi MatchParen ctermfg=230 ctermbg=234 cterm=reverse
  hi ModeMsg ctermfg=230 ctermbg=234 cterm=NONE
  hi MoreMsg ctermfg=230 ctermbg=234 cterm=NONE
  hi NonText ctermfg=230 ctermbg=234 cterm=NONE
  hi Pmenu ctermfg=230 ctermbg=234 cterm=NONE
  hi PmenuSbar ctermfg=230 ctermbg=234 cterm=NONE
  hi PmenuSel ctermfg=230 ctermbg=234 cterm=reverse
  hi PmenuThumb ctermfg=230 ctermbg=234 cterm=NONE
  hi Question ctermfg=230 ctermbg=234 cterm=NONE
  hi Search ctermfg=230 ctermbg=234 cterm=reverse
  hi SignColumn ctermfg=230 ctermbg=234 cterm=NONE
  hi SpecialKey ctermfg=230 ctermbg=234 cterm=NONE
  hi SpellBad ctermfg=230 ctermbg=234 cterm=NONE
  hi SpellCap ctermfg=230 ctermbg=234 cterm=NONE
  hi SpellLocal ctermfg=230 ctermbg=234 cterm=NONE
  hi SpellRare ctermfg=230 ctermbg=234 cterm=reverse
  hi StatusLine ctermfg=230 ctermbg=234 cterm=NONE
  hi StatusLineNC ctermfg=230 ctermbg=234 cterm=NONE
  hi TabLine ctermfg=230 ctermbg=234 cterm=NONE
  hi TabLineFill ctermfg=230 ctermbg=234 cterm=NONE
  hi TabLineSel ctermfg=230 ctermbg=234 cterm=NONE
  hi Title ctermfg=230 ctermbg=234 cterm=NONE
  hi VertSplit ctermfg=230 ctermbg=234 cterm=NONE
  hi Visual ctermfg=230 ctermbg=234 cterm=reverse
  hi VisualNOS ctermfg=230 ctermbg=234 cterm=NONE
  hi WarningMsg ctermfg=160 ctermbg=234 cterm=NONE
  hi WildMenu ctermfg=230 ctermbg=234 cterm=NONE
  hi Comment ctermfg=240 ctermbg=NONE cterm=italic
  hi Constant ctermfg=33 ctermbg=NONE cterm=NONE
  hi Error ctermfg=230 ctermbg=234 cterm=reverse
  hi Identifier ctermfg=123 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=230 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=214 ctermbg=NONE cterm=NONE
  hi Special ctermfg=33 ctermbg=NONE cterm=italic
  hi Statement ctermfg=210 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=177 ctermbg=NONE cterm=NONE
  hi Type ctermfg=220 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=33 ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=234 cterm=NONE
  hi ToolbarButton ctermfg=230 ctermbg=234 cterm=bold
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
    hi Special cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'dark_transp_bg', 0)
    hi Normal ctermfg=White ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=White ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=White ctermbg=Darkgray cterm=NONE
    hi Terminal ctermfg=White ctermbg=Darkgray cterm=NONE
  endif
  hi ColorColumn ctermfg=fg ctermbg=Darkgray cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=White ctermbg=Darkgray cterm=reverse
  hi CursorColumn ctermfg=White ctermbg=Darkgray cterm=NONE
  hi CursorLine ctermfg=White ctermbg=Darkgray cterm=NONE
  hi CursorLineNr ctermfg=White ctermbg=Darkgray cterm=NONE
  hi DiffAdd ctermfg=White ctermbg=Darkgray cterm=reverse
  hi DiffChange ctermfg=White ctermbg=Darkgray cterm=reverse
  hi DiffDelete ctermfg=White ctermbg=Darkgray cterm=reverse
  hi DiffText ctermfg=White ctermbg=Darkgray cterm=bold,reverse
  hi Directory ctermfg=White ctermbg=Darkgray cterm=NONE
  hi EndOfBuffer ctermfg=White ctermbg=Darkgray cterm=NONE
  hi ErrorMsg ctermfg=White ctermbg=Darkgray cterm=reverse
  hi FoldColumn ctermfg=White ctermbg=Darkgray cterm=NONE
  hi Folded ctermfg=White ctermbg=Darkgray cterm=italic
  hi IncSearch ctermfg=White ctermbg=Darkgray cterm=reverse
  hi LineNr ctermfg=Gray ctermbg=Darkgray cterm=NONE
  hi MatchParen ctermfg=White ctermbg=Darkgray cterm=reverse
  hi ModeMsg ctermfg=White ctermbg=Darkgray cterm=NONE
  hi MoreMsg ctermfg=White ctermbg=Darkgray cterm=NONE
  hi NonText ctermfg=White ctermbg=Darkgray cterm=NONE
  hi Pmenu ctermfg=White ctermbg=Darkgray cterm=NONE
  hi PmenuSbar ctermfg=White ctermbg=Darkgray cterm=NONE
  hi PmenuSel ctermfg=White ctermbg=Darkgray cterm=reverse
  hi PmenuThumb ctermfg=White ctermbg=Darkgray cterm=NONE
  hi Question ctermfg=White ctermbg=Darkgray cterm=NONE
  hi Search ctermfg=White ctermbg=Darkgray cterm=reverse
  hi SignColumn ctermfg=White ctermbg=Darkgray cterm=NONE
  hi SpecialKey ctermfg=White ctermbg=Darkgray cterm=NONE
  hi SpellBad ctermfg=White ctermbg=Darkgray cterm=NONE
  hi SpellCap ctermfg=White ctermbg=Darkgray cterm=NONE
  hi SpellLocal ctermfg=White ctermbg=Darkgray cterm=NONE
  hi SpellRare ctermfg=White ctermbg=Darkgray cterm=reverse
  hi StatusLine ctermfg=White ctermbg=Darkgray cterm=NONE
  hi StatusLineNC ctermfg=White ctermbg=Darkgray cterm=NONE
  hi TabLine ctermfg=White ctermbg=Darkgray cterm=NONE
  hi TabLineFill ctermfg=White ctermbg=Darkgray cterm=NONE
  hi TabLineSel ctermfg=White ctermbg=Darkgray cterm=NONE
  hi Title ctermfg=White ctermbg=Darkgray cterm=NONE
  hi VertSplit ctermfg=White ctermbg=Darkgray cterm=NONE
  hi Visual ctermfg=White ctermbg=Darkgray cterm=reverse
  hi VisualNOS ctermfg=White ctermbg=Darkgray cterm=NONE
  hi WarningMsg ctermfg=Red ctermbg=Darkgray cterm=NONE
  hi WildMenu ctermfg=White ctermbg=Darkgray cterm=NONE
  hi Comment ctermfg=Gray ctermbg=NONE cterm=italic
  hi Constant ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Error ctermfg=White ctermbg=Darkgray cterm=reverse
  hi Identifier ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=White ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Special ctermfg=Blue ctermbg=NONE cterm=italic
  hi Statement ctermfg=Red ctermbg=NONE cterm=NONE
  hi Todo ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Type ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=Blue ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=Darkgray cterm=NONE
  hi ToolbarButton ctermfg=White ctermbg=Darkgray cterm=bold
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
    hi Special cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 0
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi PopupSelected term=reverse
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  hi debugBreakpoint term=reverse
  hi debugPC term=reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: black         rgb(  0,   0,   0)        ~         Black
" Color: red           rgb(255,   0,   0)        ~         DarkRed
" Color: green         rgb(  0, 255,   0)        ~         DarkGreen
" Color: yellow        rgb(255, 255,   0)        ~         DarkYellow
" Color: blue          rgb(  0,   0, 255)        ~         DarkBlue
" Color: magenta       rgb(255,   0, 255)        ~         DarkMagenta
" Color: cyan          rgb(  0, 255, 255)        ~         DarkCyan
" Color: white         rgb(235, 235, 235)        ~         LightGrey
" Color: brightblack   rgb(210, 210, 210)        ~         DarkGrey
" Color: brightred     rgb(255, 100,   0)        ~         LightRed
" Color: brightgreen   rgb(100, 255,   0)        ~         LightGreen
" Color: brightyellow  rgb(255, 255, 100)        ~         LightYellow
" Color: brightblue    rgb(  0, 100, 255)        ~         LightBlue
" Color: brightmagenta rgb(255, 100, 255)        ~         LightMagenta
" Color: brightcyan    rgb(100, 255, 255)        ~         LightCyan
" Color: brightwhite   #e0e0ed                  231        White
" Color: cool_blue     #2f81d3                   33        Blue
" Color: earthy_brown  #6d4c41                   94        Brown
" Color: faded_walnut  #4c3b30                   94        Brown
" Color: calm_teal     #2fd381                  123        Cyan
" Color: olive_green   #8bc34a                  148        Green
" Color: light_gray    #bdbdbd                  145        Lightgray
" Color: warm_red      #d32f2f                  160        Red
" Color: soft_violet   #d06cf8                  177        Magenta
" Color: gentle_lime   #cddc39                  190        Yellow
" Color: warm_orange   #f57c00                  214        Yellow
" Color: vivid_orange  #f9a30e                  214        Yellow
" Color: light_red     #ff5b50                  210        Red
" Color: soft_coral    #e57373                  210        Lightred
" Color: soft_pink     #e58ac2                  219        Magenta
" Color: vivid_yellow  #fedf13                  220        LightYellow
" Color: misty_rose    #ffcdd2                  224        Lightred
" Color: pale_peach    #ffccbc                  224        Lightyellow
" Color: golden_yellow #fbc02d                  226        Lightyellow
" Color: soft_amber    #ffeb3b                  229        Yellow
" Color: warm_white    #fdf6e3                  230        White
" Color: dark_warm_ash #2a2a2a                  234        Darkgray
" Color: soft_charcoal #2c2c2c                  235        Darkgray
" Color: warm_ash      #3a3a3a                  236        Darkgray
" Color: dark_gray     #424242                  237        Darkgray
" Color: slate_blue    #333a56                  238        Darkblue
" Color: muted_olive   #4b4f3e                  239        Brown
" Color: medium_gray   #757575                  240        Gray
" Term colors: black red green yellow blue magenta cyan white
" Term colors: brightblack brightred brightgreen brightyellow
" Term colors: brightblue brightmagenta brightcyan brightwhite
" vim: et ts=8 sw=2 sts=2
